package com.drools.loop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HelloProcessModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HelloProcessModel() {
    }

    
    private String userlocation;
	private Integer count;
	private Integer loopcondition;
	
	
	public String getUserlocation() {
		return userlocation;
	}
	public void setUserlocation(String userlocation) {
		this.userlocation = userlocation;
	}
	public Integer getCount() {
		return count;
	}
	public void setCount(Integer count) {
		this.count = count;
	}
	public Integer getLoopcondition() {
		return loopcondition;
	}
	public void setLoopcondition(Integer loopcondition) {
		this.loopcondition = loopcondition;
	}


}